### ISSUE TITLE
не авторизует если аккаунт создан для VPS

### ISSUE THREAD

**Issue by dvasunin** [andreymal/certbot-dns-sweb#1]
Собственно, subj. Я купил у sweb-а VPS и панель управления там находится по другому адресу (vps.sweb.ru). Поэтому плагин не проходит авторизацию:
2024-08-13 23:19:32,289:INFO:certbot_dns_sweb.dns_sweb:Authenticate on SpaceWeb...
2024-08-13 23:19:32,290:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mcp.sweb.ru:443
2024-08-13 23:19:32,503:DEBUG:urllib3.connectionpool:https://mcp.sweb.ru:443 "GET /main/auth/ HTTP/11" 200 None
2024-08-13 23:19:32,779:DEBUG:urllib3.connectionpool:https://mcp.sweb.ru:443 "POST /main/auth_submit/ HTTP/11" 302 0
2024-08-13 23:19:32,781:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): vps.sweb.ru:443
2024-08-13 23:19:32,947:DEBUG:urllib3.connectionpool:https://vps.sweb.ru:443 "GET /main/ HTTP/11" 200 None
2024-08-13 23:19:32,949:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot_dns_sweb/dns_sweb.py", line 105, in _perform
    self._drop_old_txt(domain, validation_name)
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot_dns_sweb/dns_sweb.py", line 72, in _drop_old_txt
    old_txt = self._get_client().domains_dns_info_find(
              ^^^^^^^^^^^^^^^^^^
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot_dns_sweb/dns_sweb.py", line 143, in _get_client
    c = SWebClient(
        ^^^^^^^^^^^
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot_dns_sweb/sweb_client.py", line 64, in __init__
    self.login()
  File "/var/lib/certbot-env/venv/lib/python3.11/site-packages/certbot_dns_sweb/sweb_client.py", line 92, in login
    raise SWebError(f"Failed to log in (unexpected redirect {resp.url!r})")
certbot_dns_sweb.sweb_client.SWebError: Failed to log in (unexpected redirect 'https://vps.sweb.ru/main/')

Можно починить? Хотелось бы автоматически получать wildcard-certificate на домен для VPS. Плагин нужный

С уважением,
  Дмитрий

**Comment by andreymal** [comment]
Попытался что-то сделать в https://github.com/andreymal/certbot-dns-sweb/commit/3e879646111a270ef0e041abd89099091a071e23

**Comment by dvasunin** [comment]
кажется работает, спасибо! Только вот не нашел способа создать ограниченный аккаунт

**Comment by andreymal** [comment]
Ругается на «Недопустимый тип аккаунта», возможно, добавление дополнительных пользователей доступно только для ИП/юрлиц
